const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function createDataEntries() {
  try {
    // Create an array of data to be inserted
    const dataEntries = [
      {
        
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 002053',
          acquisition: '7/23/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'Sub-Station 11',
          rank: 'PCpl',
          lastName: 'Favila',
          firstName: 'Zedrick',
          middleName: 'Villaluz',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 227448',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 243872',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'Sub-Station 15',
          rank: 'PCpl',
          lastName: 'Balmeo',
          firstName: 'Jennifer',
          middleName: 'Javien',
          QLFR: 'undefined',
        },
       
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 104762',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 167996',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 168033',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 173107',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'Sub-Station 3',
          rank: 'Pat',
          lastName: 'Medina',
          firstName: 'John Arlez',
          middleName: 'Jaldo',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 175926',
          acquisition: '42837',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'Sub-Station 11',
          rank: 'PCpl',
          lastName: 'Cabauatan',
          firstName: 'Domingo',
          middleName: 'Pesito',
          QLFR: 'JR',
        },
        {
          Gtype: 'Rifle (B)',
          Gname: 'Elisco',
          caliber: '5.56',
          serialN: 'RP 233291',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 9000,
          station: 'Sub-Station 13',
          rank: 'PCpl',
          lastName: 'Laleo',
          firstName: 'Jingle',
          middleName: 'Malaggay',
          QLFR: 'undefined',
        },
        
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217948',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217751',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'ARMS',
          rank: 'PCpl',
          lastName: 'Edora',
          firstName: 'Carlo Miguel',
          middleName: 'Banez',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217859',
          acquisition: '2/14/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'ARMS LSO',
          rank: 'PCMS',
          lastName: 'De Jesus',
          firstName: 'Gigie',
          middleName: 'Nacional',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217886',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'Sub-Station 10',
          rank: 'Pat',
          lastName: 'Punsalan',
          firstName: 'Julious',
          middleName: 'Manalo',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217797',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'Sub-Station 4',
          rank: 'PCpl',
          lastName: 'Manuel',
          firstName: 'Eduardo',
          middleName: 'Bulos',
          QLFR: 'Jr',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '218001',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'Sub-Station 7',
          rank: 'PCpl',
          lastName: 'Barce',
          firstName: 'Mark Wilson',
          middleName: 'Tangub',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '217963',
          acquisition: '7/19/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'POS-SWAT South',
          rank: 'PCpl',
          lastName: 'Isaac',
          firstName: 'Ellis',
          middleName: 'Borja',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Shotgun',
          Gname: 'Escort',
          caliber: 'G12',
          serialN: '170323',
          acquisition: '7/23/2018',
          checkIn: '',
          checkOut: '',
          cost: 19092,
          station: 'Sub-Station 12',
          rank: 'PCpl',
          lastName: 'Bansen',
          firstName: 'Feliciana',
          middleName: 'Cayat',
          QLFR: 'undefined',
        },
        
    
      
        {
          Gtype: 'Rifle',
          Gname: 'Bushmaster',
          caliber: '5.56',
          serialN: 'L130958',
          acquisition: '7/16/2018',
          checkIn: '',
          checkOut: '',
          cost: 135745,
          station: 'Sub-Station 3',
          rank: 'PLT',
          lastName: 'BAUTISTA',
          firstName: 'BERNARDO',
          middleName: 'SIBUNGA II',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle',
          Gname: 'Bushmaster',
          caliber: '5.56',
          serialN: 'L082890',
          acquisition: '7/18/2018',
          checkIn: '',
          checkOut: '',
          cost: 135745,
          station: 'Sub-Station 4',
          rank: 'PEMS',
          lastName: 'Beringuel',
          firstName: 'Edgardo',
          middleName: 'Ramos',
          QLFR: 'undefined',
        },
    
        {
          Gtype: 'Rifle',
          Gname: 'Bushmaster',
          caliber: '5.56',
          serialN: 'L093015',
          acquisition: '42837',
          checkIn: '',
          checkOut: '',
          cost: 135745,
          station: 'ARMS LSO',
          rank: 'PLT',
          lastName: 'ALCANTARA',
          firstName: 'MICHELLE',
          middleName: 'TORRES',
          QLFR: 'undefined',
        },
        {
          Gtype: 'Rifle',
          Gname: 'Bushmaster',
          caliber: '5.56',
          serialN: 'L130425',
          acquisition: '7/23/2018',
          checkIn: '',
          checkOut: '',
          cost: 135745,
          station: 'POS-SWAT South',
          rank: 'PSSg',
          lastName: 'Kadil',
          firstName: 'Jonathan',
          middleName: 'Duco',
          QLFR: 'undefined',
        },// Additional Norinco CQ rifle entries
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48261556',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'Sub-Station 15',
          rank: 'PCpl',
          firstName: 'Balmeo',
          middleName: 'Jennifer',
          lastName: 'Javien',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48255578',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'Sub-Station 4',
          rank: 'PCpl',
          firstName: 'Gabano',
          middleName: 'Robert',
          lastName: 'Buenavistra Jr',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48261547',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'POS-MPQRT',
          rank: 'PCpl',
          firstName: 'Matecyeng',
          middleName: 'Freddierick',
          lastName: 'Fesway',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48255348',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'Sub-Station 11',
          rank: 'PSMS',
          firstName: 'Politud',
          middleName: 'Ariel',
          lastName: 'Podadera',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48254844',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'POS-MPQRT',
          rank: 'PCpl',
          firstName: 'Somlani',
          middleName: 'Stephen',
          lastName: 'Camilon',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48145685',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'POS-MPQRT',
          rank: 'Pat',
          firstName: 'Reovoca',
          middleName: 'Ryan',
          lastName: 'Calmada',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48254710',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'Sub-Station 9',
          rank: 'PCpl',
          firstName: 'Robledo',
          middleName: 'Romeo',
          lastName: 'Hintacutan JR',
          QLFR: 'undefined'
        },
        {
          Gtype: 'Rifle',
          Gname: 'Galil Ace 22N',
          caliber: '5.56',
          serialN: '48253946',
          acquisition: '2/15/2021',
          checkIn: '',
          checkOut: '',
          cost: 87995,
          station: 'Intel Sec',
          rank: 'PCpl',
          firstName: 'Inocencio',
          middleName: 'Edison',
          lastName: 'Estolas',
          QLFR: 'undefined'
        },
       
        
       
        
      
    ];

    // Insert data entries into the database
    const createdData = await prisma.data.createMany({
      data: dataEntries,
    });
    console.log(createdData.count);
    console.log(`${createdEntries.count} entries created.`);
  } catch (error) {
  } finally {
    await prisma.$disconnect();
  }
}

createDataEntries();
