const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();


async function createDataEntries() {
  try {
    // Create an array of data to be inserted
    const dataEntries = [
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 10191',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 8',
        rank: 'Pat',
        lastName: 'Azucena',
        firstName: 'Jaypee',
        middleName: 'Molina',
        QLFR: '',
      },
      // Add more entries below
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 11935',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Gabano',
        firstName: 'Robert',
        middleName: 'Buenavistra Jr',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 15763',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'OCOP-OACOPA',
        rank: 'PCpl',
        lastName: 'Gamayao',
        firstName: 'Jelyn',
        middleName: 'Hipos',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01863',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Pancito',
        firstName: 'Jessie',
        middleName: 'Lopez',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01865',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Garvida',
        firstName: 'John Aldrol',
        middleName: 'Bonus',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01867',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPQRT',
        rank: 'PCpl',
        lastName: 'Gedoria',
        firstName: 'Ely',
        middleName: 'Tubo',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG07374',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT North',
        rank: 'Pat',
        lastName: 'Diña',
        firstName: 'John Ray',
        middleName: 'Maldos',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG11578',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT/DS ARMS FS',
        rank: 'Pat',
        lastName: 'Andres',
        firstName: 'Jillian Agustin',
        middleName: 'Elviña',
        QLFR: '',
      },
      // Add more entries below
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG11934',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Garcia',
        firstName: 'Emmanuel',
        middleName: 'Cristobal Jr.',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG11941',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'CAS',
        rank: 'Pat',
        lastName: 'Papiona',
        firstName: 'Ronie',
        middleName: 'Sabas',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG12512',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 13',
        rank: 'Pat',
        lastName: 'Laurinaria',
        firstName: 'Marck Joe',
        middleName: 'Tadique',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG12513',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'OCOP-DEU',
        rank: 'PCpl',
        lastName: 'Las Piñas',
        firstName: 'Ricky',
        middleName: 'Alcazar',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG12518',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub Station 11',
        rank: 'Pat',
        lastName: 'Barbanida',
        firstName: 'Regina',
        middleName: '',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13645',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'POS-MPT North',
        rank: 'PCpl',
        lastName: 'Samar',
        firstName: 'Gary',
        middleName: 'Delgado',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13650',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 13',
        rank: 'Pat',
        lastName: 'Mirador',
        firstName: 'Robert',
        middleName: 'Sandoval',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13652',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Intel Sec',
        rank: 'PCpl',
        lastName: 'Vicente',
        firstName: 'Mark Raian',
        middleName: 'Dugay',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13695',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Butalid',
        firstName: 'Clyde',
        middleName: 'Paundog',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13697',
        acquisition:  '2019/12/02',
        TurnOver: '2023/7/25',
        Returned: '2023/7/30',
        cost: 23995,
        station: 'Sub-Station 10',
        rank: 'PCpl',
        lastName: 'Valenzuela',
        firstName: 'Florencio',
        middleName: 'Gumera',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13698',
        acquisition:  '2019/12/02,09/20/2019',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 14',
        rank: 'Pat',
        lastName: 'Binwag',
        firstName: 'Jan Kyle',
        middleName: 'Mora',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG13700',
        acquisition:  '2019/12/02',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 14',
        rank: 'Pat',
        lastName: 'Oliano',
        firstName: 'Anderson',
        middleName: 'Bugtong',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG14590',
        acquisition:  '2019/12/02',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'POS-MPT North',
        rank: 'PCpl',
        lastName: 'Lozano',
        firstName: 'Val Jerome',
        middleName: 'Alcarez',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG14649',
        acquisition:  '2019/12/02',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 8',
        rank: 'PCpl',
        lastName: 'Saverola',
        firstName: 'Lester Glenn',
        middleName: 'Baylon',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG14650',
        acquisition:  '2019/12/02',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 3',
        rank: 'PCpl',
        lastName: 'Nangit',
        firstName: 'Mary Jhanary',
        middleName: 'Liboon',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG14652',
        acquisition:  '2019/12/02',
        Retruned: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 10',
        rank: 'Pat',
        lastName: 'Punsalan',
        firstName: 'Julious',
        middleName: 'Manalo',
        QLFR: '',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG14653',
        acquisition:  '2019/12/02',
        TurnOver: '',
        Returned: '',
        cost: 23995,
        station: 'Sub-Station 6',
        rank: 'Pat',
        lastName: 'Banquillo',
        firstName: 'Rommel',
        middleName: 'Paat',
        QLFR: '',
      },
    ];

    // Insert data entries into the database
    const createdEntries = await prisma.Gun_Detail.createMany({
      data: dataEntries,
    });
    console.log(createdEntries.count);
    console.log(`${createdEntries.count} entries created.`);
  } catch (error) {
  } finally {
    await prisma.$disconnect();
  }
}

createDataEntries();
