const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();


async function createDataEntries() {
  try {
    // Create an array of data to be inserted
    const dataEntries = [
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L130958',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'Sub-Station 3',
        rank: 'PLT',
        lastName: 'BAUTISTA',
        firstName: 'BERNARDO',
        middleName: 'SIBUNGA II',
        QLFR: ' ',
     
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L082890',
        acquisition: '2018-7-23',
        turnOver: ' 2023-5-30',
        returned: '2023-06-3',
        cost: 135745,
        station: 'Sub-Station 4',
        rank: 'PEMS',
        lastName: 'Beringuel',
        firstName: 'Edgardo',
        middleName: 'Ramos',
        QLFR: ' ',
      
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L130958',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'Sub-Station 3',
        rank: 'PLT',
        lastName: 'BAUTISTA',
        firstName: 'BERNARDO',
        middleName: 'SIBUNGA II',
        QLFR: ' ',
  
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L082890',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'Sub-Station 4',
        rank: 'PEMS',
        lastName: 'Beringuel',
        firstName: 'Edgardo',
        middleName: 'Ramos',
        QLFR: ' ',
     
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L082898',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'Sub-Station 2',
        rank: 'Pat',
        lastName: 'Valencia',
        firstName: 'Alvin Kim',
        middleName: 'Moya',
        QLFR: ' ',
      
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L093015',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'ARMS LSO',
        rank: 'PLT',
        lastName: 'ALCANTARA',
        firstName: 'MICHELLE',
        middleName: 'TORRES',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L130425',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'POS-SWAT South',
        rank: 'PSSg',
        lastName: 'Kadil',
        firstName: 'Jonathan',
        middleName: 'Duco',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Bushmaster',
        caliber: '5.56',
        serialN: 'L130524',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 135745,
        station: 'Sub-Station 1',
        rank: 'PCpl',
        lastName: 'Arojado',
        firstName: 'Melvin',
        middleName: 'San Jose',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Norinco CQ',
        caliber: '5.56',
        serialN: 'CN 015286-15',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 69400,
        station: 'POS-TOC',
        rank: 'Pat',
        lastName: 'Galolo',
        firstName: 'Nikko',
        middleName: 'Garcia',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Norinco CQ',
        caliber: '5.56',
        serialN: 'CN 017108-15',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 69400,
        station: 'ARMS-GSS',
        rank: 'Pat',
        lastName: 'Apolinario',
        firstName: 'Noricio',
        middleName: 'Panaga',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Norinco CQ',
        caliber: '5.56',
        serialN: 'CN 019988-15',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 69400,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Manuel',
        firstName: 'Eduardo',
        middleName: 'Bulos',
        QLFR: 'Jr',
      },
      
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48261556',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Sub-Station 15',
        rank: 'PCpl',
        lastName: 'Balmeo',
        firstName: 'Jennifer',
        middleName: 'Javien',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48255578',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Gabano',
        firstName: 'Robert',
        middleName: 'Buenavistra Jr',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48261547',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'POS-MPQRT',
        rank: 'PCpl',
        lastName: 'Matecyeng',
        firstName: 'Freddierick',
        middleName: 'Fesway',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48255348',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Sub-Station 11',
        rank: 'PSMS',
        lastName: 'Politud',
        firstName: 'Ariel',
        middleName: 'Podadera',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48254844',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'POS-MPQRT',
        rank: 'PCpl',
        lastName: 'Somlani',
        firstName: 'Stephen',
        middleName: 'Camilon',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48145685',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'POS-MPQRT',
        rank: 'Pat',
        lastName: 'Reovoca',
        firstName: 'Ryan',
        middleName: 'Calmada',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48254710',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Sub-Station 9',
        rank: 'PCpl',
        lastName: 'Robledo',
        firstName: 'Romeo',
        middleName: 'Hintacutan JR',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48253946',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Intel Sec',
        rank: 'PCpl',
        lastName: 'Inocencio',
        firstName: 'Edison',
        middleName: 'Estolas',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48256810',
        acquisition: '2018-7-23',
        turnOver: ' 2023-5-30',
        returned: '2023-06-3',
        cost: 87995,
        station: 'POS-SWAT South',
        rank: 'PCpl',
        lastName: 'Jose',
        firstName: 'Jesse Raymond',
        middleName: 'Roque',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48255213',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'ARMS LSO',
        rank: 'PCMS',
        lastName: 'De Jesus',
        firstName: 'Gigie',
        middleName: 'Nacional',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48258866',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Ambrosio',
        firstName: 'Joel',
        middleName: 'Castillo',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48264826',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'Sub-Station 9',
        rank: 'PCpl',
        lastName: 'Robledo',
        firstName: 'Romeo',
        middleName: 'Hintacutan JR',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48258935',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'SWAT South',
        rank: 'PCpl',
        lastName: 'Gregorio',
        firstName: 'John Lester',
        middleName: 'Alvarez',
        QLFR: ' ',
      },
      {
        Gtype: 'Rifle',
        Gname: 'Galil Ace 22N',
        caliber: '5.56',
        serialN: '48256312',
        acquisition: '2018-7-23',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 87995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Jose',
        firstName: 'Michael Paulo',
        middleName: 'Roxas',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '164083',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'POS-SWAT North',
        rank: 'PLT',
        lastName: 'POBADORA',
        firstName: 'REGIE',
        middleName: 'BARANTES',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '169716',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 6',
        rank: 'Pat',
        lastName: 'Taboga',
        firstName: 'Joel',
        middleName: 'Lacuanan',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '170790',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 15',
        rank: 'PCpl',
        lastName: 'Balmeo',
        firstName: 'Jennifer',
        middleName: 'Javien',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '170836',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 6',
        rank: 'Pat',
        lastName: 'Taboga',
        firstName: 'Joel',
        middleName: 'Lacuanan',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '217737',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Manuel',
        firstName: 'Eduardo',
        middleName: 'Bulos Jr',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '217886',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 10',
        rank: 'Pat',
        lastName: 'Punsalan',
        firstName: 'Julious',
        middleName: 'Manalo',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '217797',
        acquisition: '2017-3-13',
        turnOver: ' 2023-5-30',
        returned: '2023-06-3',
        cost: 19092,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Manuel',
        firstName: 'Eduardo',
        middleName: 'Bulos Jr',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '218001',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 7',
        rank: 'PCpl',
        lastName: 'Barce',
        firstName: 'Mark Wilson',
        middleName: 'Tangub',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '217963',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'POS-SWAT South',
        rank: 'PCpl',
        lastName: 'Isaac',
        firstName: 'Ellis',
        middleName: 'Borja',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '170323',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 12',
        rank: 'PCpl',
        lastName: 'Bansen',
        firstName: 'Feliciana',
        middleName: 'Cayat',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '171228',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'Sub-Station 15',
        rank: 'PCpl',
        lastName: 'Balmeo',
        firstName: 'Jennifer',
        middleName: 'Javien',
        QLFR: ' ',
      },
      {
        Gtype: 'Shotgun',
        Gname: 'Escort',
        caliber: 'G12',
        serialN: '171229',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 19092,
        station: 'POS-SWAT South',
        rank: 'PSSg',
        lastName: 'Diego',
        firstName: 'Jeffrey',
        middleName: 'Dupra',
        QLFR: ' ',
      },

      //pistol 

      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 10191',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'Sub-Station 8',
        rank: 'Pat',
        lastName: 'Azucena',
        firstName: 'Jaypee',
        middleName: 'Molina',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 11935',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'Sub-Station 4',
        rank: 'PCpl',
        lastName: 'Gabano',
        firstName: 'Robert',
        middleName: 'Buenavistra Jr',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG 15763',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'OCOP-OACOPA',
        rank: 'PCpl',
        lastName: 'Gamayao',
        firstName: 'Jelyn',
        middleName: 'Hipos',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01863',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Pancito',
        firstName: 'Jessie',
        middleName: 'Lopez',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01865',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Garvida',
        firstName: 'John Aldrol',
        middleName: 'Bonus',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG01867',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'POS-MPQRT',
        rank: 'PCpl',
        lastName: 'Benavidez',
        firstName: 'Nestor',
        middleName: 'Perez III',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG07374',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'POS-MPT North',
        rank: 'Pat',
        lastName: 'Diña',
        firstName: 'John Ray',
        middleName: 'Maldos',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG11578',
        acquisition: '2017-3-13',
        turnOver: ' 2023-5-30',
        returned: '2023-06-3',
        cost: 23995,
        station: 'POS-MPT/DS ARMS FS',
        rank: 'Pat',
        lastName: 'Andres',
        firstName: 'Jillian Agustin',
        middleName: 'Elviña',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Canik Striker TP9 SF',
        caliber: '9MM',
        serialN: 'T6472-18-BG11934',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 23995,
        station: 'POS-MPT',
        rank: 'PCpl',
        lastName: 'Garcia',
        firstName: 'Emmanuel',
        middleName: 'Cristobal Jr.',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP01045',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'SWAT- North',
        rank: 'PMSg',
        lastName: 'Tabora',
        firstName: 'Ramon',
        middleName: 'Mataganas JR',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04680',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'Newly Assigned',
        rank: 'PMAJ',
        lastName: 'LLEVA',
        firstName: 'TESSIE',
        middleName: 'LANDOCAN',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04910',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'Sub-Station 6',
        rank: 'PCpl',
        lastName: 'Albaida',
        firstName: 'Romer',
        middleName: 'Laddaran',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04940',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'IDMS',
        rank: 'PSSg',
        lastName: 'Bautista',
        firstName: 'Rodolfo King',
        middleName: 'Angeles',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04946',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'Sub-Station 6',
        rank: 'PSSg',
        lastName: 'Bere',
        firstName: 'Armando',
        middleName: 'Orot',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04951',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'POS-SWAT North',
        rank: 'PSSg',
        lastName: 'Bittuwon',
        firstName: 'Wilson',
        middleName: 'Inahug',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04974',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'Sub-Station 2',
        rank: 'PSSg',
        lastName: 'Candelario',
        firstName: 'Ryan',
        middleName: 'Leonin',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP04985',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'POS-MPQRT North',
        rank: 'PSSg',
        lastName: 'Cerdon',
        firstName: 'Andrew',
        middleName: 'Enrique',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP05006',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'POS-MPT North',
        rank: 'PSSg',
        lastName: 'De Tabbali',
        firstName: 'Joylene',
        middleName: 'Siddayao',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP05012',
        acquisition: '2017-3-13',
        turnOver: ' 2023-5-30',
        returned: '2023-06-3',
        cost: 16659,
        station: 'Intel Sec',
        rank: 'PCpl',
        lastName: 'Desor',
        firstName: 'Villy',
        middleName: 'Hermo',
        QLFR: ' ',
      },
      {
        Gtype: 'Pistol',
        Gname: 'Glock 17 Gen 4',
        caliber: '9MM',
        serialN: 'PNP05027',
        acquisition: '2017-3-13',
        turnOver: '2023-6-30',
        returned: '2023-07-1',
        cost: 16659,
        station: 'POS-SWAT North',
        rank: 'PSsg',
        lastName: 'Fagayan',
        firstName: 'Jeffer Francjim',
        middleName: 'Kedawen',
        QLFR: ' ',
      },
    ];
    // Insert data entries into the database
    const createdEntries = await prisma.record.createMany({
      data: dataEntries,
    });
    console.log(createdEntries.count);
    console.log(`${createdEntries.count} entries created.`);
  } catch (error) {
  } finally {
    await prisma.$disconnect();
  }
}

createDataEntries();
